language: go


go:
- 1.11.x


script: go test -v && CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: "cnc-source-modifier.exe"
  skip_cleanup: true
  on:
    tags: true
